plugins {
    id "com.github.johnrengelman.shadow" version "5.2.0"
}

group 'me.peridot.mckdisco'
version '1.2.3'

apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

sourceCompatibility = 1.8

shadowJar {
    mergeServiceFiles()
    relocate 'api.peridot.periapi', 'me.peridot.mckdisco.libs.periapi'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    maven { url "https://jitpack.io" }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT'
    compile "com.github.P3ridot:periAPI:af8adbe0a2"
}
